### ISSUE TITLE
String to number conversion

### ISSUE THREAD

**Issue by akilbekov** [jarjan/tenge.party#11]
https://github.com/jarjan/tenge.party/blob/b9d89b06a865dc84583a7556bdcf93d12b4326e0/src/App.js#L17

тут надо поменять на что-то типа:
this.setState({ [id]: parseFloat(value) });

а то приложение падает если убрать галку и ввести новое значение

**Comment by jarjan** [comment]
@akilbekov спасибо за репорт, на днях исправлю.

**Comment by jarjan** [comment]
Исправлено тут: https://github.com/jarjan/tenge.party/pull/12
