### ISSUE TITLE
Implement new design

### ISSUE THREAD

**Issue by jarjan** [jarjan/tenge.party#15]
Figma link: https://www.figma.com/file/aTMe6mgXykYpqmbJXfIuKGh4/%E2%82%B8%F0%9F%8E%89?node-id=0%3A1

Screenshot:
![](https://user-images.githubusercontent.com/836813/52377106-222d4880-2a64-11e9-846b-c51989555ca9.png)

**Comment by ramyamahi** [comment]
@jarjan Do you need new design as like in the below screenshot?

**Comment by jarjan** [comment]
@ramyamahi doesn't need to 100% accurate. Can be used as reference.

**Comment by ramyamahi** [comment]
Ok. I can start

**Comment by ramyamahi** [comment]
#17

**Comment by ramyamahi** [comment]
@jarjan New design completed fully with responsive. Please review and merge it #17
![new-design](https://user-images.githubusercontent.com/41541742/66270950-73513e80-e876-11e9-829e-bccdf29ef888.png)

**Comment by jarjan** [comment]
@ramyamahi great!
Will take a look tomorrow and merge if all good. Thanks a lot! And happy hacktoberfest :)

**Comment by jarjan** [comment]
@ramyamahi thanks again!

**Comment by ramyamahi** [comment]
Learned lot. Thanks a lot! @jarjan
