### ISSUE TITLE
[bug] Галочка "на руки" при нажатии на Enter

### ISSUE THREAD

**Issue by daitsuna-group** [jarjan/tenge.party#5]
Если убрать галочку "на руки" и потом ввести новую сумму и нажать Enter. То галочка "на руки" автоматически включается.

**Comment by jarjan** [comment]
@daitsuna-group я в процессе переписания проекта, так что этот баг исчезнет в ближайщем будушем.
https://github.com/jarjan/tenge.party/pull/2
